### ISSUE TITLE
Docker driver ignores docker_host  in molecule.yml

### ISSUE THREAD

**Issue by knagamin** [ansible-community/molecule-docker#1]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/knagamin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/knagamin/.local/lib/python3.8/site-packages/ansible
  executable location = /home/knagamin/.local/bin/ansible
  python version = 3.8.5 (default, Jul 31 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
molecule 3.0.4
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Molecule runs with a correct docker host when the host is specified in molecule.yml like:
```
driver:
  name: docker
platforms:
  - name: instance01
    docker_host: tcp://docker.test.local:2375
```

# Actual Behaviour

Docker driver will always try to connect to localhost if `DOCKER_HOST` is not defined.
Because the driver refers to default host (unix://var/run/docker.sock) instead of that.
Then `docker_host` attribute is ignored.
This issue will produce the sanity check failure and runtime error. 

Workaround for this is using `DOCKER_HOST` environment variable.

**Comment by ssbarnea** [comment]
Closing as wont fix due to https://github.com/ansible-community/molecule-docker/discussions/85 so people would not imagine that bugs or features would magically be fixed by someone else. If you want to help, pull requests are likely the best way, start with simple ones.
