### ISSUE TITLE
Unsupported parameters for (community.docker.docker_container) module: command_handling

### ISSUE THREAD

**Issue by mconigliaro** [ansible-community/molecule-docker#150]
`TASK [Wait for instance(s) creation to complete] *******************************
failed: [localhost] (item={'started': 1, 'finished': 0, 'ansible_job_id': '232388391867.85284', 'results_file': '/Users/mike/.ansible_async/232388391867.85284', 'changed': True, 'failed': False, 'item': {'image': 'ubuntu:20.04', 'name': 'focal'}, 'ansible_loop_var': 'item'}) => {"ansible_job_id": "232388391867.85284", "ansible_loop_var": "item", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "232388391867.85284", "ansible_loop_var": "item", "changed": true, "failed": false, "finished": 0, "item": {"image": "ubuntu:20.04", "name": "focal"}, "results_file": "/Users/mike/.ansible_async/232388391867.85284", "started": 1}, "msg": "Unsupported parameters for (community.docker.docker_container) module: command_handling Supported parameters include: api_version, auto_remove, blkio_weight, ca_cert, cap_drop, capabilities, cgroup_parent, cleanup, client_cert, client_key, command, comparisons, container_default_behavior, cpu_period, cpu_quota, cpu_shares, cpus, cpuset_cpus, cpuset_mems, debug, default_host_ip, detach, device_read_bps, device_read_iops, device_requests, device_write_bps, device_write_iops, devices, dns_opts, dns_search_domains, dns_servers, docker_host, domainname, entrypoint, env, env_file, etc_hosts, exposed_ports, force_kill, groups, healthcheck, hostname, ignore_image, image, init, interactive, ipc_mode, keep_volumes, kernel_memory, kill_signal, labels, links, log_driver, log_options, mac_address, memory, memory_reservation, memory_swap, memory_swappiness, mounts, name, network_mode, networks, networks_cli_compatible, oom_killer, oom_score_adj, output_logs, paused, pid_mode, pids_limit, privileged, published_ports, pull, purge_networks, read_only, recreate, removal_wait_timeout, restart, restart_policy, restart_retries, runtime, security_opts, shm_size, ssl_version, state, stop_signal, stop_timeout, storage_opts, sysctls, timeout, tls, tls_hostname, tmpfs, tty, ulimits, use_ssh_client, user, userns_mode, uts, validate_certs, volume_driver, volumes, volumes_from, working_dir"}`

I don't know what this means, but I fixed it by editing `.venv/lib/python3.8/site-packages/molecule_docker/playbooks/create.yml` and commenting out this line: `command_handling: "{{ item.command_handling | default('compatibility') }}"`

**Comment by sverrehu** [comment]
Thank you, @mconigliaro! I ran into the same error, and your fix helped me get past it.
