### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by hylaride** [ansible-community/molecule-docker#152]
Any chance you guys could cut a release so we can take advantage of [issue 122](https://github.com/ansible-community/molecule-docker/pull/122 )?  More and more of us are on apple silicon.

**Comment by ssbarnea** [comment]
I am making a new release these days but it will likely be the Final version, as in the last ever. Plugin popularity dropped as many people switched to podman and we failed to find anyone that can actively afford to maintain this plugin in more than an year.

I really cannot spend more days on doing the required chores as this prevents me from working on other more important changes on molecule itself.

**Comment by ssbarnea** [comment]
https://github.com/ansible-community/molecule-docker/releases/tag/v2.0.0

**Comment by hylaride** [comment]
@ssbarnea Thanks so much!
