### ISSUE TITLE
Supplied Dockerfile COPY/ADD instructions fail

### ISSUE THREAD

**Issue by ggolin** [ansible-community/molecule-docker#168]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.0.0
molecule --version
molecule, version 1.19.1
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of pip

# Desired Behaviour

Given: a user provided Dockerfile with COPY or ADD instructions local files should be copied/added to the container

# Actual Behaviour (Bug report only)

molecule create fails to find the local files/directories that should be copied to the container.

**Comment by ssbarnea** [comment]
Closing as fixed, if you see not working feel free to make a PR to fix as nobody else is likely to fix it for you. Also locking the ticket after as it is too old and too many things from inside were changed over the years.
