### ISSUE TITLE
Make a new release to fix `COPY`/`ADD` instructions

### ISSUE THREAD

**Issue by nre-ableton** [ansible-community/molecule-docker#179]
I see that https://github.com/ansible-community/molecule-docker/issues/168 has been fixed in the `main` branch, but it hasn't been released yet. It would be nice to be able to use this feature, is a new release planned soon?

**Comment by ssbarnea** [comment]
@nre-ableton next time ping use on matrix/irc and one of us will make a new release. I am doing it now.
