### ISSUE TITLE
Package depends on a prerelease

### ISSUE THREAD

**Issue by auburus** [ansible-community/molecule-docker#28]
Hi!

I have noticed that after https://github.com/ansible-community/molecule-docker/pull/19, the repository now depends on an alpha version of molecule (version 3.2.0a0).
```
...
# These are required in actual runtime:
install_requires =
    molecule >= 3.2.0a0
```

 I was installing it with pipenv, and now I need to set the following for it to work in my `Pipfile`:
```
[pipenv]

allow_prereleases = true
```

While there is a workaround, I was wondering if it would be possible to change the dependency to `molecule>=3.1.5`, the last stable one, or if there is some functionality that is only present in the alpha version.

Thanks!

(And I am happy to create that PR to reduce the overhead 😊 )

**Comment by tadeboro** [comment]
It looks like `molecule-docker` version `0.3.3` should be marked as a prerelease since it depends on the prerelease `molecule` version. This will sort itself out when the molecule 3.2.0 will be released. In the meantime, the simplest thing to do is to cap the `molecule-docker` package in your Pipfile. Something like this should work:

    [packages]
    molecule-docker = "<0.3"

**Comment by auburus** [comment]
Thank you very much for your explanation. Just checked that your answer works perfectly (I wasn't aware that the "extras" packages could be point to a particular version too). So I will close this issue 👍

For completion, this is how my Pipfile looks.

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
molecule-docker = "<0.3"
molecule = {extras = ["docker"], version = "*"}


[packages]
ansible = "*"

[requires]
python_version = "3.6"
```
