### ISSUE TITLE
Tox failures due to the upgrade of importlib-metadata

### ISSUE THREAD

**Issue by abtreece** [ansible-community/molecule-docker#31]
Receiving test failures due to the recent upgrade of `importlib-metadata` to [v3.0.0](https://github.com/python/importlib_metadata/releases/tag/v3.0.0)

```
virtualenv 20.2.0 has requirement importlib-metadata<3,>=0.12; python_version < "3.8", but you have importlib-metadata 3.0.0.
```

https://github.com/pypa/virtualenv/blob/ced984abfd4f1531f9075113e77af7ec01479d29/setup.cfg#L47

https://github.com/pypa/virtualenv/issues/2019

**Comment by ssbarnea** [comment]
I think you already know how to fix. For stuff like this is easier to just make PR to fix it. Until upstream fixes it add a local condition to help pip make a good decision, with comment linking the upstream bug.

**Comment by abtreece** [comment]
The upstream issue seemed like an easy fix so I took a stab at that PR. I wanted to raise it as a known issue here so there was explanation for the test failures, etc. The upstream PR has been merged and released... ⚡ 

fixed by https://github.com/pypa/virtualenv/pull/2021
