### ISSUE TITLE
Better way to allow molecule.yml to pass all allowed arguments to create.yml?

### ISSUE THREAD

**Issue by ragingpastry** [ansible-community/molecule-docker#35]
I have just submitted a merge request to add the `links` parameter to create.yml so that we can specify Docker links in our molecule file by default. However I was wondering if there was a better way to do this?

Has there been any discussion about how to programmatically generate a create.yml which allows all available options for the docker_container ansible module to be passed from molecule.yml?

**Comment by decentral1se** [comment]
> Has there been any discussion about how to programmatically generate a create.yml which allows all available options for the docker_container ansible module to be passed from molecule.yml?

It was a subject of discussion for a while but the effort was deemed too much especially when it was much simpler to just wait until someone needed a new parameter and then simply add it and make the release.

Tickets for the docker plugin should land on https://github.com/ansible-community/molecule-docker I think?

Thanks for the PR :heart:

**Comment by decentral1se** [comment]
> Tickets for the docker plugin should land on https://github.com/ansible-community/molecule-docker I think?

Lol, I am totally lost, this is that repo! :) Sorry for confusion... a lot of churn...

**Comment by ssbarnea** [comment]
Closing as wont fix due to https://github.com/ansible-community/molecule-docker/discussions/85 so people would not imagine that bugs or features would magically be fixed by someone else. If you want to help, pull requests are likely the best way, start with simple ones.
