### ISSUE TITLE
documentation: volumes vs volume_mounts

### ISSUE THREAD

**Issue by dschier-wtd** [ansible-community/molecule-docker#4]
# Issue Type

- Bug report (in documentation)

# Molecule and Ansible details

In the documentation <https://molecule.readthedocs.io/en/stable/configuration.html#docker>, you can find the hint, that one should configure 'volumes' for docker. At some points in the documentation, you can still find 'volume_mounts', which does not work.

I hope, you can have a look at some leftovers (volume_mount).

Thanks a lot for the cool work!

**Comment by ssbarnea** [comment]
Closing as wont fix due to https://github.com/ansible-community/molecule-docker/discussions/85 so people would not imagine that bugs or features would magically be fixed by someone else. If you want to help, pull requests are likely the best way, start with simple ones.
