### ISSUE TITLE
Systemd 248+ support / workarounds

### ISSUE THREAD

**Issue by mrzor** [ansible-community/molecule-docker#53]
Greetings,

I believe I've experienced the effects of https://github.com/systemd/systemd/issues/19245 (I believe) in that systemd containers will not function properly anymore with `systemd 248.2-2-arch`. This makes `molecule-docker` unsuitable for testing purposes for impacted hosts (Arch Linux starting last month, FC34 (?), soon more (?)).

While I can, and will, turn to other molecule plugins, I'm very much interested in ways to fix this or to workaround it.

#### Diagnostics

What happens is that there is only one systemd process in the container at PID 1 and that's it.

I wasn't able to get any logs out of systemd, or any kind of output.  - so, no journal, and console doesn't print or write anything as far as I can tell.

Question: Are there ways to troubleshoot this further?

**Comment by ssbarnea** [comment]
Use of systemd under docker was always problematic and not recommended use case. There is nothing molecule driver can do about that. If you need systemd, you are likely to want to use real VMs. Please use https://github.com/ansible-community/molecule/discussions next time.
